#springdoc:
#  # ???: application/json
#  # request media type ? ?? ?
#  default-consumes-media-type: application/json
#
#  # ???: */*
#  # response media type ? ?? ?
#  default-produces-media-type: application/json
#
#  # ????? ???? ui ????? ??
#  swagger-ui:
#
#    #   ?? ? : /swagger-ui.html
#    #   Swagger HTML ?? ??
#    path: /swagger-ui.html
#
#    #   swagger-ui? ??? ??? ??
#    enabled: true
#
#  # ??? api?? ??
#  api-docs:
#
#    #   ??? : /v3/api-docs
#    #   spring boot ? ??????? api? OpenAPI 3? ???? json ??? ??? ??
#    path: /swagger/api-docs
#
#    #   ??? api??? ???? ??
#    enabled: true